# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62dbb5d2c7214b163c3dd5e2c1ca9ab164dc53a7378ffa2f0c0015189bed8a4482f20f5d6ba1acf63fe419dad8f9424588ca6deaae93796ff29c5dc70fed95d0

test:
  secret_key_base: 93671181a014743b02c746ad8e92e2ba77056eb2e9edcad2776e2dfdc1d721c2510400eda29bee59a889b7c0f32ddfd16227d7de36573607c6e00886bd167316

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
